[package]
name = "waveshare-scservo"
version = "0.1.0"
edition = "2024"
authors = ["Louis Schell <louis.schell1@gmx.de>"]
description = "Waveshare SCServo protocol in embedded-hal"
keywords = ["embedded", "waveshare", "servo", "SC09", "SC15"]
license = "MIT"

[dependencies]
embedded-hal = "1.0.0"
embedded-io = "0.7.1"
embedded-io-async = "0.7.0"
defmt = { version = "1.0.1", optional = true }
device-driver = {version = "1.0.7", default-features = false, features = ["dsl"]}
embedded-hal-async = "1.0.0"

[features]
default = ["scscl", "sms_sts"]
std = []
defmt = ["dep:defmt"]

# Support for SCSCL/SC series (potentiometer, big-endian)
scscl = []
# Support for SMS/STS series (magnetic encoder, little-endian)
sms_sts = []